import math
import numpy as np

from sklearn.cluster import KMeans

from qiskit.quantum_info import Operator, Statevector, SparsePauliOp
from qiskit.circuit.library import real_amplitudes
from qiskit_aer.primitives import EstimatorV2, SamplerV2

from qiskit_algorithms import VQD
from qiskit_algorithms.state_fidelities import ComputeUncompute
from qiskit_algorithms.optimizers import COBYLA


def next_power_of_two(x: int) -> int:
    """
    Compute the next power of 2 greater than or equal to x.
    :param x: Input integer
    :return: Smallest power of 2 greater than or equal to x
    """
    return 1 if x <= 1 else 2 ** math.ceil(math.log2(x))


def pad_symmetric_matrix_to_power_of_two(L: np.ndarray):
    """
    Pad a symmetric square matrix with zeros so its dimension becomes a power of 2.
    :param L: Input symmetric square matrix
    :return: Padded matrix and original dimension
    """
    L = np.asarray(L, dtype=float)

    if L.ndim != 2 or L.shape[0] != L.shape[1]:
        raise ValueError("L must be a square matrix.")

    if not np.allclose(L, L.T, atol=1e-10):
       raise ValueError("L must be symmetric.")

    m = L.shape[0]
    dim = next_power_of_two(m)

    if dim == m:
        return L.copy(), m

    L_pad = np.zeros((dim, dim), dtype=float)
    L_pad[:m, :m] = L
    return L_pad, m


def matrix_to_sparse_pauli_op(L: np.ndarray) -> SparsePauliOp:
    """
    Convert a matrix into a SparsePauliOp representation.
    :param L: Input matrix
    :return: SparsePauliOp associated with the matrix
    """
    op = Operator(L)
    return SparsePauliOp.from_operator(op)


def statevector_from_ansatz(ansatz, parameters):
    """
    Build the statevector obtained by assigning parameters to an ansatz circuit.
    :param ansatz: Parameterized quantum circuit
    :param parameters: Values assigned to the ansatz parameters
    :return: Statevector generated by the bound ansatz
    """
    bound = ansatz.assign_parameters(parameters)
    return Statevector.from_instruction(bound)


def solve_lowest_eigenpairs_vqd(
    L: np.ndarray,
    k: int,
    reps: int = 4,
    maxiter: int = 1000,
    seed: int = 42,
    betas=None,
):
    np.random.seed(seed)

    L_pad, original_dim = pad_symmetric_matrix_to_power_of_two(L)
    dim = L_pad.shape[0]
    n_qubits = int(math.log2(dim))

    hamiltonian = matrix_to_sparse_pauli_op(L_pad)

    ansatz = real_amplitudes(
        num_qubits=n_qubits,
        reps=reps,
        entanglement="full",
    )

    estimator = EstimatorV2()
    sampler = SamplerV2()
    fidelity = ComputeUncompute(sampler)

    from qiskit_algorithms.optimizers import SLSQP
    optimizer = SLSQP(maxiter=maxiter)

    if betas is None:
        evals_exact = np.linalg.eigvalsh(L_pad)
        spectral_scale = max(1.0, float(np.max(np.abs(evals_exact))))
        betas = [5.0 * spectral_scale] * k

    history = []

    def callback(eval_count, params, value, metadata, step):
        history.append((step, eval_count, float(np.real(value))))

    vqd = VQD(
        estimator=estimator,
        fidelity=fidelity,
        ansatz=ansatz,
        optimizer=optimizer,
        k=k,
        betas=betas,
        callback=callback,
    )

    result = vqd.compute_eigenvalues(hamiltonian)

    eigenvalues = np.array(result.eigenvalues, dtype=float)
    eigenvectors = []

    for params in result.optimal_points:
        sv = statevector_from_ansatz(ansatz, params)
        eigenvectors.append(np.asarray(sv.data, dtype=complex))

    eigenvectors = np.array(eigenvectors).T

    idx = np.argsort(eigenvalues)
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:, idx]

    return eigenvalues, eigenvectors, L_pad, original_dim, history


def spectral_embedding_from_eigenvectors(eigenvectors: np.ndarray, original_dim: int, k: int):
    """
    Build the spectral embedding from the first k eigenvectors, discarding padded rows.
    :param eigenvectors: Matrix whose columns are eigenvectors
    :param original_dim: Original matrix dimension before padding
    :param k: Number of eigenvectors used in the embedding
    :return: Row-normalized spectral embedding
    """
    U = eigenvectors[:original_dim, :k]

    U = np.real(U)

    norms = np.linalg.norm(U, axis=1, keepdims=True)
    norms[norms < 1e-12] = 1.0
    Y = U / norms
    return Y


def run_kmeans_on_embedding(Y: np.ndarray, n_clusters: int, seed: int = 42):
    """
    Run k-means clustering on a spectral embedding.
    :param Y: Spectral embedding matrix
    :param n_clusters: Number of clusters
    :param seed: Random seed
    :return: Predicted labels and fitted KMeans object
    """
    kmeans = KMeans(n_clusters=n_clusters, random_state=seed, n_init=10)
    labels = kmeans.fit_predict(Y)
    return labels, kmeans


if __name__ == "__main__":
    L = np.array([
        [1.0, 0.8, 0.2, 0.1],
        [0.8, 1.0, 0.1, 0.2],
        [0.2, 0.1, 1.0, 0.75],
        [0.1, 0.2, 0.75, 1.0],
    ], dtype=float)

    k_eigs = 2

    eigenvalues, eigenvectors, L_pad, original_dim, history = solve_lowest_eigenpairs_vqd(
        L=L,
        k=k_eigs,
        reps=10,
        maxiter=5000,
        seed=42
    )

    print("Approximate eigenvalues (ascending order):")
    print(eigenvalues)

    print("\nApproximate eigenvectors (columns):")
    print(np.real(eigenvectors[:original_dim, :]))

    Y = spectral_embedding_from_eigenvectors(
        eigenvectors=eigenvectors,
        original_dim=original_dim,
        k=k_eigs
    )

    print("\nSpectral embedding Y:")
    print(Y)

    labels, kmeans = run_kmeans_on_embedding(Y, n_clusters=2, seed=42)

    print("\nK-means labels:")
    print(labels)

    evals_classic, evecs_classic = np.linalg.eigh(L)
    idx = np.argsort(evals_classic)
    evals_classic = evals_classic[idx]
    evecs_classic = evecs_classic[:, idx]

    print("\nClassical eigenvalues:")
    print(evals_classic[:k_eigs])

    print("\nClassical eigenvectors (first k, columns):")
    print(evecs_classic[:, :k_eigs])